### ISSUE TITLE
[component]: Tooltip

### ISSUE THREAD

**Issue by gfellerph** [gfellerph/artifact-test#2]
### Description

A tooltip shows short, additional information on focusable elements.

### Design

https://google.ch

### Tokens

- [X] Tokens for this component are ready

### Tasks

```[tasklist]
### Tasks
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Design review
```
