### ISSUE TITLE
[component]: awef

### ISSUE THREAD

**Issue by gfellerph** [gfellerph/artifact-test#3]
### Description

aewf

### Design

https://google.ch

### Tokens

- [ ] Tokens for this component are ready

### Tasks

```[tasklist]
- [ ] HTML/CSS implementation
- [ ] Web component implementation
- [ ] Documentation in Storybook
- [ ] Design review
```
